export const assetConstants = {
    GET_ASSET_LIST: 'GET_ASSET_LIST',
    CHANGE_PAGE: 'CHANGE_PAGE',
    SET_SORT: 'SET_SORT',
    SET_FILTER_TYPE: 'SET_FILTER_TYPE',
    SEARCH: 'SEARCH',
    SET_FIRST_SHOW_ASSET: 'SET_FIRST_SHOW_ASSET',
};
